"""
Django settings for adhd_print_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Data directory for database and other data files
DATA_DIR = Path(os.environ.get('ADHD_PRINT_DATA_DIR', BASE_DIR / 'data'))
DATA_DIR.mkdir(exist_ok=True)  # Ensure the data directory exists


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-@7hl1gc!by=rsk4c9c5@woy9ps5f*55lv*4o#)29f9b1wt5&(a'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

# Parse ALLOWED_HOSTS from environment variable (comma-separated)
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', 'testserver,127.0.0.1,localhost')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adhd_print_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adhd_print_project.wsgi.application'
ASGI_APPLICATION = 'adhd_print_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configurable database location - defaults to ./data/adhd_print.db

DATABASE_NAME = os.environ.get('ADHD_PRINT_DB_NAME', 'adhd_print.db')
DATABASE_PATH = DATA_DIR / DATABASE_NAME

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files for development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise configuration for static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True  # Allows serving files from STATICFILES_DIRS in development
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh static files in development

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/tasks/'
LOGOUT_REDIRECT_URL = '/'

# Email settings for user registration and notifications
# Default to console backend in development, SMTP in production
if DEBUG:
    # Development: Use console backend unless explicitly overridden
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND', 
        'django.core.mail.backends.console.EmailBackend'
    )
else:
    # Production: Use SMTP backend by default
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND', 
        'django.core.mail.backends.smtp.EmailBackend'
    )

# SMTP Configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')  # Default to Gmail SMTP
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes', 'on')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes', 'on')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@adhd-print.local')

# Email timeout settings
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '60'))  # 60 seconds default timeout

# Account activation settings
ACCOUNT_ACTIVATION_DAYS = int(os.environ.get('ACCOUNT_ACTIVATION_DAYS', '7'))  # Days before activation link expires

# Admin site configuration
ADMIN_URL = 'admin/'

# Printer configuration - configurable via environment variables
PRINTER_HOST = os.environ.get('ADHD_PRINT_PRINTER_HOST', '192.168.1.40')
PRINTER_PORT = int(os.environ.get('ADHD_PRINT_PRINTER_PORT', '9100'))
PRINTER_USE_GRAPHICS = os.environ.get(
    'ADHD_PRINT_USE_GRAPHICS', 'True').lower() in (
        'true', '1', 'yes', 'on')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ASGI Configuration
ASGI_APPLICATION = 'adhd_print_project.asgi.application'

# Background Jobs Configuration
BACKGROUND_JOBS_ENABLED = os.environ.get(
    'BACKGROUND_JOBS_ENABLED', 'True').lower() in (
        'true', '1', 'yes', 'on')
MAINTENANCE_SCHEDULE_HOUR = int(os.environ.get('MAINTENANCE_SCHEDULE_HOUR', '2'))
MAINTENANCE_SCHEDULE_MINUTE = int(os.environ.get('MAINTENANCE_SCHEDULE_MINUTE', '0'))

# CSRF Configuration for Docker and Production
# Trust the X-Forwarded-Proto header from reverse proxies
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins - include your domain(s)
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',') if origin.strip()]
else:
    # Default trusted origins based on ALLOWED_HOSTS
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if host not in ['testserver', '127.0.0.1', 'localhost']:
            # Add both http and https variants for external domains
            CSRF_TRUSTED_ORIGINS.extend([
                f'http://{host}',
                f'https://{host}'
            ])

# CSRF cookie settings for container environments
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'csrftoken'

# Session settings for container environments  
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours
