[program:adhd-print-django]
command=/opt/adhd-print/venv/bin/python /opt/adhd-print/manage.py runserver 127.0.0.1:8000
directory=/opt/adhd-print
user=adhd
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/adhd-print/django.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
environment=DJANGO_SETTINGS_MODULE="adhd_print_project.settings",PATH="/opt/adhd-print/venv/bin:%(ENV_PATH)s"

[program:adhd-print-worker]
command=/opt/adhd-print/venv/bin/python /opt/adhd-print/manage.py qcluster
directory=/opt/adhd-print
user=adhd
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/adhd-print/worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
environment=DJANGO_SETTINGS_MODULE="adhd_print_project.settings",PATH="/opt/adhd-print/venv/bin:%(ENV_PATH)s"

[group:adhd-print]
programs=adhd-print-django,adhd-print-worker
priority=999