# Generated by Django 5.2.7 on 2025-11-02 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('templates_processed', models.IntegerField(default=0)),
                ('instances_created', models.IntegerField(default=0)),
                ('instances_cleaned', models.IntegerField(default=0)),
                ('templates_cleaned', models.IntegerField(default=0)),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_periodic', models.BooleanField(default=False, help_text='Check if this is a repeating task')),
                ('start_date', models.DateField(blank=True, help_text='Start date for periodic tasks', null=True)),
                ('periodicity_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='How often the task repeats', max_length=20, null=True)),
                ('periodicity_detail', models.JSONField(blank=True, help_text='Additional details for periodicity (e.g., weekdays for weekly tasks)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for periodic tasks (leave empty for no end)', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('periodic_parent', models.ForeignKey(blank=True, help_text='Reference to the original periodic task template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_instances', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_method', models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)')], help_text='Method used for printing', max_length=10)),
                ('print_type', models.CharField(choices=[('single_task', 'Single Task'), ('task_hierarchy', 'Task with Subtasks'), ('todays_tasks', "Today's Tasks"), ('bulk_print', 'Bulk Print Operation')], help_text='Type of print operation', max_length=15)),
                ('success', models.BooleanField(default=True, help_text='Whether the print operation was successful')),
                ('tasks_attempted', models.IntegerField(default=1, help_text='Number of tasks attempted to print')),
                ('tasks_successful', models.IntegerField(default=0, help_text='Number of tasks successfully printed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if print failed')),
                ('printer_config', models.JSONField(blank=True, default=dict, help_text='Printer configuration at time of print (for debugging)')),
                ('print_settings', models.JSONField(blank=True, default=dict, help_text='Print settings used (graphics mode, paper size, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Print operation duration in milliseconds', null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the print operation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Primary task being printed (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Print Log',
                'verbose_name_plural': 'Print Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_method', models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)')], default='local', help_text='Preferred printing method', max_length=10)),
                ('printer_settings', models.JSONField(blank=True, default=dict, help_text='General printer settings (paper size, quality, etc.)')),
                ('server_printing_enabled', models.BooleanField(default=False, help_text='Whether server-based printing is available for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
