# Generated by Django 5.2.7 on 2025-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='Whether this task has been printed'),
        ),
    ]
