# Generated by Django 5.2.7 on 2025-10-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurring',
        ),
    ]
