# Generated by Django 5.2.7 on 2025-11-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_is_printed_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='periodic_parent',
        ),
    ]
