# Generated by Django 5.2.7 on 2025-10-31 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for periodic tasks (leave empty for no end)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_periodic',
            field=models.BooleanField(default=False, help_text='Check if this is a repeating task'),
        ),
        migrations.AddField(
            model_name='task',
            name='periodic_parent',
            field=models.ForeignKey(blank=True, help_text='Reference to the original periodic task template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodic_instances', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='periodicity_detail',
            field=models.JSONField(blank=True, help_text='Additional details for periodicity (e.g., weekdays for weekly tasks)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='periodicity_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='How often the task repeats', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for periodic tasks', null=True),
        ),
    ]
