# Generated by Django 5.2.7 on 2025-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_periodic_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='periodicity_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('every_x_days', 'Every X Days'), ('every_x_weeks', 'Every X Weeks'), ('every_x_months', 'Every X Months')], help_text='How often the task repeats', max_length=20, null=True),
        ),
    ]
