# Generated by Django 5.2.7 on 2025-10-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_periodic_task_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('templates_processed', models.IntegerField(default=0)),
                ('instances_created', models.IntegerField(default=0)),
                ('instances_cleaned', models.IntegerField(default=0)),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
