# Generated by Django 5.2.7 on 2025-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_done_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français')], default='en', help_text='Preferred language for UI and emails', max_length=10),
        ),
    ]
