# Generated by Django 5.2.7 on 2025-10-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='templates_cleaned',
            field=models.IntegerField(default=0),
        ),
    ]
