# Generated by Django 5.2.7 on 2025-11-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_maintenancelog_templates_cleaned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_method', models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)'), ('auto', 'Auto-detect Best Method')], default='server', help_text='Preferred printing method', max_length=10)),
                ('preferred_local_printer', models.JSONField(blank=True, default=dict, help_text='Stored local printer configuration')),
                ('printer_settings', models.JSONField(blank=True, default=dict, help_text='General printer settings (paper size, quality, etc.)')),
                ('local_printing_enabled', models.BooleanField(default=False, help_text='Whether local printing is available for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
