# Generated by Django 5.2.7 on 2025-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='printing_method',
            field=models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)')], default='server', help_text='Preferred printing method', max_length=10),
        ),
    ]
