# Generated by Django 5.2.7 on 2025-11-02 11:39

from django.db import migrations


def convert_auto_to_server(apps, schema_editor):
    """Convert any 'auto' printing method values to 'server'"""
    UserProfile = apps.get_model('tasks', 'UserProfile')
    updated_count = UserProfile.objects.filter(printing_method='auto').update(printing_method='server')
    if updated_count > 0:
        print(f"Converted {updated_count} user profiles from 'auto' to 'server' printing method")


def reverse_convert_auto_to_server(apps, schema_editor):
    """Reverse migration - this is not reversible since we can't know which were originally 'auto'"""
    # Cannot reliably reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_auto_printing_method'),
    ]

    operations = [
        migrations.RunPython(convert_auto_to_server, reverse_convert_auto_to_server),
    ]
