# Generated by Django 5.2.7 on 2025-11-02 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_convert_auto_to_server_printing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_method', models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)')], help_text='Method used for printing', max_length=10)),
                ('print_type', models.CharField(choices=[('single_task', 'Single Task'), ('task_hierarchy', 'Task with Subtasks'), ('todays_tasks', "Today's Tasks"), ('bulk_print', 'Bulk Print Operation')], help_text='Type of print operation', max_length=15)),
                ('success', models.BooleanField(default=True, help_text='Whether the print operation was successful')),
                ('tasks_attempted', models.IntegerField(default=1, help_text='Number of tasks attempted to print')),
                ('tasks_successful', models.IntegerField(default=0, help_text='Number of tasks successfully printed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if print failed')),
                ('printer_config', models.JSONField(blank=True, default=dict, help_text='Printer configuration at time of print (for debugging)')),
                ('print_settings', models.JSONField(blank=True, default=dict, help_text='Print settings used (graphics mode, paper size, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Print operation duration in milliseconds', null=True)),
                ('task', models.ForeignKey(blank=True, help_text='Primary task being printed (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who initiated the print operation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Log',
                'verbose_name_plural': 'Print Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
