# Generated by Django 5.2.7 on 2025-11-02 12:04

from django.db import migrations, models


def migrate_printing_preferences(apps, schema_editor):
    """Migrate existing user preferences to new server_printing_enabled logic"""
    UserProfile = apps.get_model('tasks', 'UserProfile')
    
    # Update existing users who had server printing method to enable server printing
    server_users_updated = UserProfile.objects.filter(
        printing_method='server'
    ).update(server_printing_enabled=True)
    
    # Update all users to use local printing as default method
    # (except those who explicitly chose server and we just enabled server for them)
    local_users_updated = UserProfile.objects.filter(
        printing_method='local'
    ).update(printing_method='local')  # This is redundant but explicit
    
    print(f"Migration completed:")
    print(f"  - {server_users_updated} users with server printing method now have server printing enabled")
    print(f"  - All users now default to local printing method")


def reverse_migrate_printing_preferences(apps, schema_editor):
    """Reverse the migration - not fully reversible since we lose some information"""
    UserProfile = apps.get_model('tasks', 'UserProfile')
    
    # This is not perfectly reversible, but we'll do our best
    # Users with server printing enabled get set back to server method
    UserProfile.objects.filter(
        server_printing_enabled=True
    ).update(printing_method='server')
    
    # All others get local method (which was the old logic anyway)
    UserProfile.objects.filter(
        server_printing_enabled=False
    ).update(printing_method='local')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_print_log'),
    ]

    operations = [
        # First, add the new field
        migrations.AddField(
            model_name='userprofile',
            name='server_printing_enabled',
            field=models.BooleanField(default=False, help_text='Whether server-based printing is available for this user'),
        ),
        # Run the data migration
        migrations.RunPython(migrate_printing_preferences, reverse_migrate_printing_preferences),
        # Then alter the printing_method field
        migrations.AlterField(
            model_name='userprofile',
            name='printing_method',
            field=models.CharField(choices=[('server', 'Server-based Printing'), ('local', 'Local Printing (USB/Serial)')], default='local', help_text='Preferred printing method', max_length=10),
        ),
        # Finally, remove the old field
        migrations.RemoveField(
            model_name='userprofile',
            name='local_printing_enabled',
        ),
    ]
